### ISSUE TITLE
AWS Code|build|pipelines|deploy y otras yerbas

### ISSUE THREAD

**Issue by rcor** [CRDevOpsCloudNative/comunidad#3]
# Información general del evento

**Nombre completo**: Rodolfo Cordero Sancho
**Correo electrónico**: rcor.cr@gmail.com
**Nombre de empresa/organización o independiente**: Intive

**Tipo de evento**: Charla
**Titulo del evento**: AWS Code|build|pipelines|deploy y otras yerbas 
**Descripción**:
En la charla se explicará 3 productos del catálogo de AWS los cuales son Codebuild, Codepipeline y Codedeploy. Se hablará del modelo costos, como se implementan, que beneficios, limitantes y complicaciones se pueden tener a la hora de implementarse La charla será dividida en dos secciones
* Parte teórica. Se hablará sobre que es y para que sirve cada uno de los productos, y como estos pueden funcionar de manera individual y conjunto. Se detallará los requerimientos, conceptos, limitantes y casos de uso

* Parte práctica: Se mostrará un ejemplo usando las 3 herramientas en conjunto para ver como se despliega la aplicación en una instancia ec2 
**Audiencia**: Principiantes 

**En caso de tener patrocinio por favor indique la empresa**: 

**Comentarios para los organizadores**:

**Comment by murillodigital** [comment]
@rcor  muchas gracias por tu propuesta y será un gran gusto que presentés para la comunidad! Nos podrias confirmar si tenés disponibilidad para el Jueves 15 de Abril?

**Comment by rcor** [comment]
@murillodigital tengo que lavar ropa ese dia, pero con gusto aparto la fecha

**Comment by murillodigital** [comment]
Evento agendado en MeetUp  (https://www.meetup.com/devops-cloudnative-costarica/events/276234986/) y en el CNCF Chapter.
