### ISSUE TITLE
4 encuentros de un taller de lectura 

### ISSUE THREAD

**Issue by rcor** [CRDevOpsCloudNative/comunidad#4]
# Información general del evento

**Nombre completo**: Rodolfo Cordero Sancho
**Correo electrónico**: rcor.cr@gmail.com
**Nombre de empresa/organización o independiente**: Intive

**Tipo de evento**: Taller de lectura 
**Titulo del evento**: 4 encuentros de un taller de lectura 
**Descripción**:

Se propondrá 4 lecturas (capítulos de libros) que serán elegidos y distribuidos en formato digital. Los cuales tendrán una temática de administración, tecnológica. 
Los encuentros tendrán una duración de 30-45 minutos, una vez a la semana. Uno de los miembros tomara el rol de moderador. 
Cada reunión se propondrá una pregunta basada en la lectura las cuales los miembros deberán de desarrollar 
El moderador podrá según la cantidad de participantes dividirlo en grupos con un moderador para que discutan entre ellos el contenido de el o los capítulos leídos. Los últimos 15 minutos cada moderador de cada grupo expondrá las ideas expuestas 

**Audiencia**: TPA

**En caso de tener patrocinio por favor indique la empresa**: 

**Comentarios para los organizadores**:

**Comment by murillodigital** [comment]
@rcor me parece fenomenal la idea, me interesa sin embargo convocar participación del resto de la comunidad, con que seamos unas 5 o 6 personas ya tenemos "quorum", quisiera proponer el tema en la próxima reunión de la comunidad el próximo miercoles 3 de febrero y ojalá conseguir de una vez a los primeros participantes. Estarías disponible para presentar la idea y contestar preguntas?

**Comment by rcor** [comment]
@murillodigital si me parece bien

**Comment by murillodigital** [comment]
Se introdujo el tema en la reunión de la comunidad, ya tenemos participantes y canal en Slack!
