### ISSUE TITLE
Kubernetes networking deep dive

### ISSUE THREAD

**Issue by electrocucaracha** [CRDevOpsCloudNative/comunidad#5]
# Información general del evento

Los sistemas distribuidos nos permiten balancear la carga de trabajo entre componentes interconectados. Kubernetes es un orquestrador de contenedores permite distribuir la carga de trabajo entre varios nodos de computo. Es por ello que resulta vital conocer la manera en que realiza la conexión de los distintos recursos. En esta charla se explicara a detalle la manera en que Kubernetes realiza la conexión y comunicación de contenedores.

**Nombre completo**: Victor Joel Morales Ruvalcaba
**Correo electrónico**: chipahuac@hotmail.com
**Nombre de empresa/organización o independiente**: Samsung

**Tipo de evento**: Charla
**Titulo del evento**: Kubernetes networking deep dive
**Descripción**:
* Comprensión general de proceso de creación de un Pod.
* Recorrido de paquetes(Mismo nodo).
* Recorrido de paquetes(Distintos nodo).
* Roles y funcionales de kube-proxy y distintos CNIs. 

**Audiencia**: Intermedios
**Comentarios para los organizadores**:

**Comment by murillodigital** [comment]
@electrocucaracha muchas gracias por tu propuesta y será un gran gusto que presentés para la comunidad! Nos podrias confirmar si tenés disponibilidad para el Jueves 13 de Mayo?

**Comment by electrocucaracha** [comment]
@murillodigital si puedo ese dia, lo reservo de una vez

**Comment by murillodigital** [comment]
Calendarizado evento en meetup y bevy!
